Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,3 @@
-
 name: Build Kernel
 
 on:
@@ -26,12 +25,10 @@ jobs:
     - name: Set up ccache
       uses: hendrikmuhs/ccache-action@v1.2
 
-    # Rest of your steps...
-
     - name: GetTime
       id: get_time
       run: |
-        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT
+        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M)" >> $GITHUB_ENV
 
     - name: Build Kernel
       run: |
@@ -39,7 +36,8 @@ jobs:
           git clone https://github.com/ruben1863/android_gcc_6.4.1_arm-eabi gcc
         fi
         mkdir -p out
-        export CROSS_COMPILE=${PWD}/gcc/bin/arm-eabi-
+        cd kernel-4.4  # Navigate to the kernel directory
+        export CROSS_COMPILE=${PWD}/../../gcc/bin/arm-eabi-  # Adjust the path as needed
         export USE_CCACHE=1
         export ARCH=arm
         export SUBARCH=arm
@@ -49,7 +47,7 @@ jobs:
 
     - name: Upload zImage-dtb
       run: |
-        curl -T out/arch/arm/boot/zImage-dtb https://bashupload.com/ --output upload_link
+        curl -T out/arch/arm/boot/zImage-dtb https://bashupload.com/ --output upload_link || { echo "Upload failed"; exit 1; }
         UPLOAD_LINK=$(< upload_link)
         echo "Uploaded file link: $UPLOAD_LINK"
       env:
